spring.application.name=com.icronic-Sangeetha

server.port=8085

spring.datasource.url=jdbc:mysql://springboot-sangeetha-deneth-eyes.f.aivencloud.com:14271/defaultdb?sslMode=REQUIRED&createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_WH4jgD2JsAwPNJVkinG
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#JWT CONFIGURATION
jwt.secret=SANGEETHASPRINGBOOTAPPPROJECTcREATEDbYdENETHaSapRIVATEpROJECTpLEASEcHANGEtHISinPRODUCtion1234
jwt.access.token.expiration=1800000
jwt.refresh.token.expiration=604800000

#STORAGE CONFIGURATION
file.storage.song.path=uploads/songs
file.storage.image.path=uploads/images
app.base.url=http://localhost:8085

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-swallow-size=-1

#E-MAIL/SMTP CONFIGURATION
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=deneth.private@gmail.com
spring.mail.password=xbpkeagrrsqznocv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

#FRONTEND
app.frontend.url=http://localhost:4200

#GEMINI CONFIGURATIONS
gemini.api.key=AIzaSyDapioYfRP0b_kJBOvu9eUvvtP7UAXBjPI
google.gemini.model=gemini-2.5-flash,gemini-2.5-flash-lite,
